<?php

namespace GYL\ProveedorBundle\Repository;

/**
 * BackupUserDataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BackupUserDataRepository extends \Doctrine\ORM\EntityRepository
{
}
