<?php

namespace GYL\ProveedorBundle\Repository;

/**
 * DatoExentoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DatoExentoRepository extends \Doctrine\ORM\EntityRepository
{
}
