<?php

namespace GYL\ProveedorBundle\Repository;

/**
 * EstadoEvaluacionGerenciaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EstadoEvaluacionGerenciaRepository extends \Doctrine\ORM\EntityRepository
{
}
