<?php

namespace GYL\ProveedorBundle\Repository;

/**
 * EstadoEvaluacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EstadoEvaluacionRepository extends \Doctrine\ORM\EntityRepository
{
}
