<?php

namespace GYL\ProveedorBundle\Repository;

/**
 * GerenciaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GerenciaRepository extends \Doctrine\ORM\EntityRepository
{
}
