<?php

namespace GYL\ProveedorBundle\Repository;

/**
 * ImpuestoIIbbRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImpuestoIibbRepository extends \Doctrine\ORM\EntityRepository
{
}
