<?php

namespace GYL\ProveedorBundle\Repository;

/**
 * ImpuestoIvaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImpuestoIvaRepository extends \Doctrine\ORM\EntityRepository
{
}
