<?php

namespace GYL\ProveedorBundle\Repository;

/**
 * ImpuestoGananciasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImpuestoGananciasRepository extends \Doctrine\ORM\EntityRepository
{
}
