<?php

namespace GYL\ProveedorBundle\Repository;

/**
 * Impuesto_sussRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImpuestoSussRepository extends \Doctrine\ORM\EntityRepository
{
}
