<?php

namespace GYL\ProveedorBundle\Repository;

/**
 * ObservacionEvaluacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ObservacionEvaluacionRepository extends \Doctrine\ORM\EntityRepository
{
    
    public function setInactivoByProveedorTimeline ($proveedorEvaluacionId, $timelineId) {
        $conn = $this->getEntityManager()->getConnection();
        
        $sql = " UPDATE observacion_evaluacion oe
                 INNER JOIN tipo_observacion too ON too.id = oe.id_tipo_observacion
                 SET activo = 0
                 WHERE too.id_tipo_timeline = :timelineId AND id_proveedor_evaluacion = :proveedorEvaluacionId";

        $stmt = $conn->prepare($sql);
        $stmt->bindValue('timelineId', $timelineId);
        $stmt->bindValue('proveedorEvaluacionId', $proveedorEvaluacionId);
        $stmt->execute();
        
        return $stmt->rowCount();
    }
    
}
