<?php

namespace GYL\ProveedorBundle\Repository;

/**
 * ProveedorRepresentanteApoderadoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProveedorRepresentanteApoderadoRepository extends \Doctrine\ORM\EntityRepository
{
}
