<?php

namespace GYL\ProveedorBundle\Repository;

/**
 * ProveedorDatoBancarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProveedorDatoBancarioRepository extends \Doctrine\ORM\EntityRepository
{
}
