<?php

namespace GYL\ProveedorBundle\Repository;

/**
 * ProveedorRubroRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProveedorRubroRepository extends \Doctrine\ORM\EntityRepository
{
	public function findByIdDenoms($ids)
    {
        $conn = $this->getEntityManager()->getConnection();

        $sql = "SELECT r.id, r.denominacion rubro, cat.denominacion categoria, p.fecha_baja 
		FROM rubro_clase r 
		INNER JOIN rubro cat ON r.id_rubro = cat.id
		LEFT JOIN proveedor_rubro p ON r.id_rubro = p.id_rubro_clase
		WHERE r.id IN (:ids) AND p.fecha_baja IS NULL";
        $stmt = $conn->prepare($sql);
        $stmt->bindValue('ids', $ids);
        $stmt->execute();

        

        // returns an array of arrays (i.e. a raw data set)
        return $stmt->fetchAll();
    }
}
