<?php

namespace GYL\ProveedorBundle\Repository;

/**
 * ProveedorActividadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProveedorActividadRepository extends \Doctrine\ORM\EntityRepository
{

    public function findByIdDenoms($idDatoPersonal)
    {
        $conn = $this->getEntityManager()->getConnection();

        $sql = "SELECT p.id, t.denominacion, g.denominacion as denominacion_grupo, s.denominacion as denominacion_seccion FROM proveedor_actividad as p 
        LEFT JOIN tipo_actividad as t ON p.id_tipo_actividad=t.id 
        LEFT JOIN tipo_actividad_grupo as g ON t.id_grupo=g.id 
        LEFT JOIN  tipo_actividad_seccion as s  ON g.id_seccion= s.id 
        WHERE p.id_proveedor_dato_personal = :id AND p.fecha_baja IS NULL";
        $stmt = $conn->prepare($sql);
        $stmt->bindValue('id', $idDatoPersonal);
        $stmt->execute();

        // returns an array of arrays (i.e. a raw data set)
        return $stmt->fetchAll();
    }


}
