<?php

namespace GYL\ProveedorBundle\Repository;

/**
 * ProveedorDatoImpositivosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProveedorDatoImpositivosRepository extends \Doctrine\ORM\EntityRepository
{
}
