<?php

namespace GYL\ProveedorBundle\Repository;

/**
 * MiembrosUteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProveedorUteMiembrosRepository extends \Doctrine\ORM\EntityRepository
{
}
