<?php

namespace GYL\ProveedorBundle\Repository;

/**
 * ProveedorDeclaracionJuradaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProveedorDeclaracionJuradaRepository extends \Doctrine\ORM\EntityRepository
{
}
