<?php

namespace GYL\ProveedorBundle\Repository;

/**
 * ProveedorDomicilioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProveedorDomicilioRepository extends \Doctrine\ORM\EntityRepository
{
}
