<?php

namespace GYL\ProveedorBundle\Repository;

/**
 * ProveedorDatoGcshmRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProveedorDatoGcshmRepository extends \Doctrine\ORM\EntityRepository
{
}
