<?php

namespace GYL\ProveedorBundle\Repository;

/**
 * ProveedorPersonaJuridicaMiembrosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProveedorPersonaJuridicaMiembrosRepository extends \Doctrine\ORM\EntityRepository
{
}
