<?php

namespace GYL\ProveedorBundle\Repository;

/**
 * ProveedorDocumentacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProveedorDocumentacionRepository extends \Doctrine\ORM\EntityRepository
{
}
