<?php

namespace GYL\ProveedorBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DatosContactoAdicionalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProveedorDatoContactoRepository extends EntityRepository
{

}
