<?php

namespace GYL\ProveedorBundle\Repository;

/**
 * RubroClaseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RubroClaseRepository extends \Doctrine\ORM\EntityRepository
{
}
