<?php

namespace GYL\ProveedorBundle\Repository;

/**
 * TipoPersonaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoPersonaRepository extends \Doctrine\ORM\EntityRepository
{
}
