<?php

namespace GYL\ProveedorBundle\Repository;

/**
 * TipoObservacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoObservacionRepository extends \Doctrine\ORM\EntityRepository
{
}
