<?php

namespace GYL\ProveedorBundle\Repository;

/**
 * TipoProveedorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoProveedorRepository extends \Doctrine\ORM\EntityRepository
{
}
