<?php

namespace GYL\ProveedorBundle\Repository;

/**
 * TipoIvaInscriptoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoIvaInscriptoRepository extends \Doctrine\ORM\EntityRepository
{
}
