<?php

namespace GYL\ProveedorBundle\Repository;

/**
 * TipoActividadSeccionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoActividadSeccionRepository extends \Doctrine\ORM\EntityRepository
{
}
