<?php

namespace GYL\ProveedorBundle\Repository;

/**
 * TipoActividadGrupoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoActividadGrupoRepository extends \Doctrine\ORM\EntityRepository
{
}
