<?php

namespace GYL\ProveedorBundle\Repository;

/**
 * TipoDocumentacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoDocumentacionRepository extends \Doctrine\ORM\EntityRepository
{
}
