<?php

namespace GYL\ProveedorBundle\Repository;

/**
 * TipoPersonaJuridicaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoPersonaJuridicaRepository extends \Doctrine\ORM\EntityRepository
{
}
