<?php

namespace GYL\ProveedorBundle\Repository;

/**
 * TipoTimelineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoTimelineRepository extends \Doctrine\ORM\EntityRepository
{
}
