<?php

namespace GYL\ProveedorBundle\Repository;

/**
 * UteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UteRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByExistingDenom($denominacion, $idDatoPersonal)
    {
        $conn = $this->getEntityManager()->getConnection();

        $sql = "SELECT * FROM adif_proveedores.proveedor_ute WHERE denominacion = :denominacion AND id_proveedor_dato_personal != :iddatopersonal";
        $stmt = $conn->prepare($sql);
        $stmt->bindValue('denominacion', $denominacion);
        $stmt->bindValue('iddatopersonal', $idDatoPersonal);

        $stmt->execute();

        // returns an array of arrays (i.e. a raw data set)
        return $stmt->fetchAll();
    }
}
