<?php

namespace GYL\UsuarioBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * InvitacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InvitacionRepository extends EntityRepository
{
    
}
