security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager

                login_path: /login
                check_path: /login_check
                always_use_default_target_path: false
                #default_target_path: /cuentacorriente
                default_target_path: after_login_redirect

            logout:
                path: fos_user_security_logout 
                target: fos_user_security_login
            anonymous: true

    access_control:
        - { path: ^/invitacion/crear$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/cuentacorriente$, role: ROLE_USER }
        - { path: ^/cuentacorrienteajax$, role: ROLE_USER, method: [POST]}
        - { path: ^/admin/, role: ROLE_ADMIN }
