fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@GYLUsuarioBundle/Resources/config/routing/change_password.xml"
    prefix: /
    #resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    #prefix: /profile

gyl_usuario_invitacion:
    resource: "@GYLUsuarioBundle/Controller"
    prefix: /
    type: annotation
